FROM vlaship/ubuntu_git_gradle

RUN git clone https://github.com/vlaship/msgServerSimple \
&& cd msgServer \
&& gradle build \
&& cd build/libs \
&& mv *.jar /server.jar

ENTRYPOINT ["java","-jar","server.jar"]