insert into edge (city_from, city_to, duration) values ('San Francisco', 'Oakland', 16);
insert into edge (city_from, city_to, duration) values ('Oakland', 'San Francisco', 16);
insert into edge (city_from, city_to, duration) values ('San Francisco', 'mountain view', 37);
insert into edge (city_from, city_to, duration) values ('mountain view', 'San Francisco', 37);
insert into edge (city_from, city_to, duration) values ('San Francisco', 'palo alto', 32);
insert into edge (city_from, city_to, duration) values ('palo alto', 'San Francisco', 32);
insert into edge (city_from, city_to, duration) values ('mountain view', 'San jose', 17);
insert into edge (city_from, city_to, duration) values ('San jose', 'mountain view', 17);
insert into edge (city_from, city_to, duration) values ('mountain view', 'palo alto', 12);
insert into edge (city_from, city_to, duration) values ('palo alto', 'mountain view', 12);
insert into edge (city_from, city_to, duration) values ('mountain view', 'santa clara', 14);
insert into edge (city_from, city_to, duration) values ('santa clara', 'mountain view', 14);
insert into edge (city_from, city_to, duration) values ('mountain view', 'sunnyvale', 7);
insert into edge (city_from, city_to, duration) values ('sunnyvale', 'mountain view', 7);
insert into edge (city_from, city_to, duration) values ('mountain view', 'cupertino', 9);
insert into edge (city_from, city_to, duration) values ('cupertino', 'mountain view', 9);
insert into edge (city_from, city_to, duration) values ('San jose', 'santa cruz', 39);
insert into edge (city_from, city_to, duration) values ('santa cruz', 'San jose', 39);
insert into edge (city_from, city_to, duration) values ('San jose', 'pleasanton', 42);
insert into edge (city_from, city_to, duration) values ('pleasanton', 'San jose', 42);
insert into edge (city_from, city_to, duration) values ('San jose', 'santa clara', 12);
insert into edge (city_from, city_to, duration) values ('santa clara', 'San jose', 12);